spring.datasource.url=jdbc:postgresql://dpg-d6of9jer433s73d0lo10-a/users_iszt

spring.datasource.username=users_iszt_user
spring.datasource.password=9pCPkKgM6jW2lNBPRWCt4UwOWAWiJlSh

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
